### ISSUE TITLE
One potential item for the cop

### ISSUE THREAD

**Issue by pravi** [rubocop-hq/packaging-style-guide#4] opened 2020-08-25 20:55 UTC
The right solution may be in gem2deb-test-runner, but I want to share the issue here.

When autopkgtest is run, lib directory is renamed to force loading the library from system path as installed by the .deb package. But this means bundler cannot find the library if Gemfile references gemspec.

Current work around,
https://salsa.debian.org/ruby-team/ruby-combustion/-/blob/master/debian/patches/adjust-Gemfile.patch

Best solution may be for gem2deb-test-runner to modify Gemfile to replace gemspec with the gem name.

**Comment by pravi** [comment] 2020-08-25 21:11
Another package that need this work around https://salsa.debian.org/ruby-team/ruby-puma-worker-killer/-/blob/master/debian/patches/autopkgtest-fix.patch

**Comment by pravi** [comment] 2020-08-25 21:13
ruby-ahoy-email and ruby-sping also affected. Many others might be affected as well, because we were not able to successfully enable tests when the tests used a dummy rails app and bundler.

Update: ruby-invisible-captcha is another package affected by this issue.

**Comment by terceiro** [comment] 2020-10-02 17:50
I don't think this is something that rubocop-packaging can do much about. 

for example I looked into puma_worker_killer, and 1the problem is that the tests are explicitly using bundler, and we already know that this is a problem, and there is no single way of fixing this for all packages.

**Comment by utkarsh2102** [comment] 2020-10-02 20:35
As discussed, this isn't a candidate for `rubocop-packaging` to handle. So closing this.

Thanks!

**Closed as completed by utkarsh2102** 2020-10-02 20:35 UTC
